import FWCore.ParameterSet.Config as cms
#from PhysicsTools.SelectorUtils.pfJetIDSelector_cfi import pfJetIDSelector
#from CMGTools.External.pujetidproducer_cfi import stdalgos, chsalgos

#useAOD = True

analyzer = cms.EDAnalyzer("Analyzer",
                          #hggPhotonIDConfiguration = hggPhotonIDCuts,
                          doGenParticles   = cms.bool(True),
                          doCalib   = cms.bool(False),
                          runOnParticleGun = cms.bool(False),
                          runOnSherpa      = cms.bool(True),
                          runOnVtx         = cms.bool(False),            
                          runOnReco         = cms.bool(False),            
                          dumpPhotons      = cms.bool(False),
                          dumpElectrons      = cms.bool(False),
                          dumpMuons        = cms.bool(False),
                          dumpJets         = cms.bool(False),
                          dumpSubJets      = cms.bool(False),
                          dumpPDFSystWeight = cms.bool(False),  
                          dumpGenScaleSystWeights = cms.bool(False),
                          dumpGenScalSystWeight = cms.bool(False),  
                          doGenJets            = cms.bool(True),
                          isAOD            = cms.bool(False), #### actually configured through run_data_74x.py
                          runphoIDVID      = cms.bool(False),
                          runeleIDVID      = cms.bool(False),
                          runphoMVAID      = cms.bool(False),
                          runeleMVAID      = cms.bool(False),
                          development      = cms.bool(False),
                          addFilterInfoAOD     = cms.bool(False),
                          addFilterInfoMINIAOD = cms.bool(False),
                          
                          triggerResults       = cms.InputTag("TriggerResults", "", "HLT"),

                          GenJetLabel          = cms.InputTag("ak4GenJets"),
                          genParticleSrc    = cms.InputTag("genParticles"),
                          generatorLabel    = cms.InputTag("generator"),
                          LHEEventLabel     = cms.InputTag("externalLHEProducer"),
                          newParticles      = cms.vint32(4000011, 4000013, 1000006, 1000022, 1000024, 1000025, 35),
                          pileupCollection  = cms.InputTag("addPileupInfo"),
                          VtxLabel          = cms.InputTag("offlinePrimaryVertices"),
                          VtxBSLabel        = cms.InputTag("offlinePrimaryVerticesWithBS"),
                          rhoLabel          = cms.InputTag("fixedGridRhoFastjetAll"),
                          rhoCentralLabel   = cms.InputTag("fixedGridRhoFastjetCentralNeutral"),
                          electronSrc       = cms.InputTag("selectedPatElectrons"),
                          calibelectronSrc     = cms.InputTag("calibratedElectrons"),
                          photonSrc         = cms.InputTag("selectedPatPhotons"),
                          calibphotonSrc       = cms.InputTag("calibratedPhotons"),
                          muonSrc           = cms.InputTag("selectedPatMuons"),
                          gsfTrackSrc       = cms.InputTag("electronGsfTracks"),
                          ebReducedRecHitCollection = cms.InputTag("reducedEcalRecHitsEB"),
                          eeReducedRecHitCollection = cms.InputTag("reducedEcalRecHitsEE"),
                          esReducedRecHitCollection = cms.InputTag("reducedEcalRecHitsES"),
                          recoPhotonSrc             = cms.InputTag("gedPhotons"),
                          TrackLabel                = cms.InputTag("generalTracks"),
                          gsfElectronLabel          = cms.InputTag("gsfElectrons"),
                          PFAllCandidates           = cms.InputTag("particleFlow"),
                          #ak4JetSrc                 = cms.InputTag("selectedPatJets"),
                          ak4JetSrc                 = cms.InputTag("selectedPatJetsAK4PFCHS"),
                          ak8JetSrc                 = cms.InputTag("selectedPatJetsAK8PFCHS"),
                          
                          phoLooseIdMap = cms.InputTag("egmPhotonIDs:cutBasedPhotonID-Spring15-25ns-V1-standalone-loose"),
                          phoMediumIdMap = cms.InputTag("egmPhotonIDs:cutBasedPhotonID-Spring15-25ns-V1-standalone-medium"),
                          phoTightIdMap = cms.InputTag("egmPhotonIDs:cutBasedPhotonID-Spring15-25ns-V1-standalone-tight"),
                          phoMVAValuesMap = cms.InputTag("photonMVAValueMapProducer:PhotonMVAEstimatorRun2Spring15NonTrig25nsV2Values"),
                          phoChargedIsolation       = cms.InputTag("photonIDValueMapProducer:phoChargedIsolation"),
                          phoNeutralHadronIsolation = cms.InputTag("photonIDValueMapProducer:phoNeutralHadronIsolation"),
                          phoPhotonIsolation        = cms.InputTag("photonIDValueMapProducer:phoPhotonIsolation"),
                          phoWorstChargedIsolation  = cms.InputTag("photonIDValueMapProducer:phoWorstChargedIsolation"),
                          phoChargedIsolation_CITK        = cms.InputTag("egmPhotonIsolationMiniAOD:h+-DR030-"),
                          phoPhotonIsolation_CITK         = cms.InputTag("egmPhotonIsolationMiniAOD:gamma-DR030-"),
                          phoNeutralHadronIsolation_CITK  = cms.InputTag("egmPhotonIsolationMiniAOD:h0-DR030-"),
                          phoChargedIsolation_PUPPI       = cms.InputTag("egmPhotonIsolationMiniAODPUPPI:h+-DR030-"),
                          phoPhotonIsolation_PUPPI        = cms.InputTag("egmPhotonIsolationMiniAODPUPPI:gamma-DR030-"),
                          phoNeutralHadronIsolation_PUPPI = cms.InputTag("egmPhotonIsolationMiniAODPUPPI:h0-DR030-"),

                          packedPFCands   = cms.InputTag("packedPFCandidates"),
                          eleVetoIdMap    = cms.InputTag("egmGsfElectronIDs:cutBasedElectronID-Spring15-25ns-V1-standalone-veto"),
                          eleLooseIdMap   = cms.InputTag("egmGsfElectronIDs:cutBasedElectronID-Spring15-25ns-V1-standalone-loose"),
                          eleMediumIdMap  = cms.InputTag("egmGsfElectronIDs:cutBasedElectronID-Spring15-25ns-V1-standalone-medium"),
                          eleTightIdMap   = cms.InputTag("egmGsfElectronIDs:cutBasedElectronID-Spring15-25ns-V1-standalone-tight"),
                          eleHLTIdMap     = cms.InputTag("egmGsfElectronIDs:cutBasedElectronHLTPreselection-Summer16-V1"),
                          eleHEEPIdMap    = cms.InputTag("egmGsfElectronIDs:heepElectronID-HEEPV70"),
                          eleMVAValuesMap = cms.InputTag("electronMVAValueMapProducer:ElectronMVAEstimatorRun2Spring16GeneralPurposeV1Values"),
                          eleNonTrgMVAValuesMap = cms.InputTag("electronMVAValueMapProducer:ElectronMVAEstimatorRun2Spring15NonTrig25nsV1Values"),
                          eleTrgMVAValuesMap = cms.InputTag("electronMVAValueMapProducer:ElectronMVAEstimatorRun2Spring15Trig25nsV1Values"),
                          eleMVAHZZValuesMap = cms.InputTag("electronMVAValueMapProducer:ElectronMVAEstimatorRun2Spring16HZZV1Values"),
                          elePFClusEcalIsoProducer = cms.InputTag("electronEcalPFClusterIsolationProducer"),
                          elePFClusHcalIsoProducer = cms.InputTag("electronHcalPFClusterIsolationProducer"),
                          
)

